networks:
  intemporal:

services:

  jaeger:
    image: jaegertracing/jaeger:2.12.0
    command: [ --set=receivers.otlp.protocols.grpc.endpoint=0.0.0.0:4317 ]
    networks:
      - intemporal
    ports:
      - 16686:16686
      - 4317

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.135.0
    command: [ --config=/etc/otel.yml ]
    volumes:
      - ./docker/otel.yml:/etc/otel.yml
    networks:
      - intemporal
    ports:
      - 4317:4317
      - 4318:4318
    depends_on:
      - jaeger

  foundation:
    image: "foundationdb/foundationdb:7.1.60"
    environment:
      FDB_NETWORKING_MODE: host
    entrypoint: ["/usr/bin/tini", "-g", "--", "sh", "/fdb-init.bash"]
    volumes:
      - ./docker/fdb-init.bash:/fdb-init.bash
      - ./docker/fdb.bash:/var/fdb/scripts/fdb.bash
      - ./docker:/var/fdb/run:rw
    ports:
      - 4500:4500/tcp

  postgresql:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
